In [2]:
import sys
import numpy as np 
import pandas as pd

sys.version

'3.12.12 (main, Jan 14 2026, 23:36:32) [Clang 21.1.4 ]'

In [3]:
from pathlib import Path 

raw_path = Path("../data") / "raw"

df = pd.read_csv(raw_path / "devices.csv")

In [4]:
df.head()

,device_hash_id,source,station_hash_id,device_id,name,device_model,max_power
0,3223f6ee747ede5f21c5858a9ddc6fce,2,e2afd8af435a86d8bfe72dcbe937a5d6,REDACTED,50KTL-M3(COM3-13),SUN2000-50KTL-M3,55.0
1,15de11e7df8168a60db8f55669d66e76,2,b59685487a1fc5712e03c264f70cb656,REDACTED,INV-1,SUN2000-50KTL-M3,55.0
2,a2bc58707e3ac5b41a4a8f49900d675b,1,2c85da17f3ac504327da04874ef1a701,REDACTED,NaN,1603,100.0
3,44aaeb88850bacfd88cce3f4fc07566f,2,e2afd8af435a86d8bfe72dcbe937a5d6,REDACTED,50KTL-M3(COM3-19),SUN2000-50KTL-M3,55.0
4,94aedd81bad035cc73968fe5b06f808a,2,19477f81a2058c850a09310b7795fd4f,REDACTED,INV-6T2289011404,SUN2000-40KTL-M3,44.0

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 66 entries, 0 to 65
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   device_hash_id   66 non-null     str
 1   source           66 non-null     int64
 2   station_hash_id  66 non-null     str
 3   device_id        66 non-null     str
 4   name             53 non-null     str
 5   device_model     65 non-null     str
 6   max_power        53 non-null     float64
dtypes: float64(1), int64(1), str(5)
memory usage: 3.7 KB

# Exploring energy dataset

In [5]:
enery_hour_df = pd.read_csv(raw_path / "energy_production_hourly_inverter.csv")

In [6]:
enery_hour_df.head()

,device_hash_id,measured_ts,total_produced_energy,source,ac_power,dc_power,efficiency,temperature,count_state_on,count_state_off,count_state_error,count_state_total,perc_state_on,perc_state_off,perc_state_error
0,0e23b9fa122a5a1e1f2005e1f8ccb4ae,2024-12-31 23:00:00,0.00,2,0.000000,0.000018,0.0000,0.000000,0.0,1.0,0.0,1.0,0.00,1.00,0.0
1,0e23b9fa122a5a1e1f2005e1f8ccb4ae,2025-01-01 05:00:00,0.00,2,0.000000,0.000002,0.0000,10.400000,0.0,1.0,0.0,1.0,0.00,1.00,0.0
2,0e23b9fa122a5a1e1f2005e1f8ccb4ae,2025-01-01 06:00:00,0.01,2,0.000583,0.000002,8.5525,12.850000,9.0,3.0,0.0,12.0,0.75,0.25,0.0
3,0e23b9fa122a5a1e1f2005e1f8ccb4ae,2025-01-01 07:00:00,0.03,2,0.064500,0.000002,37.2000,20.691667,12.0,0.0,0.0,12.0,1.00,0.00,0.0
4,0e23b9fa122a5a1e1f2005e1f8ccb4ae,2025-01-01 08:00:00,0.05,2,0.110333,0.000002,49.6000,26.725000,12.0,0.0,0.0,12.0,1.00,0.00,0.0

In [7]:
enery_hour_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112249 entries, 0 to 112248
Data columns (total 15 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   device_hash_id         112249 non-null  str
 1   measured_ts            112249 non-null  str
 2   total_produced_energy  112249 non-null  float64
 3   source                 112249 non-null  int64
 4   ac_power               112249 non-null  float64
 5   dc_power               112249 non-null  float64
 6   efficiency             112249 non-null  float64
 7   temperature            112249 non-null  float64
 8   count_state_on         112249 non-null  float64
 9   count_state_off        112249 non-null  float64
 10  count_state_error      112249 non-null  float64
 11  count_state_total      112249 non-null  float64
 12  perc_state_on          112249 non-null  float64
 13  perc_state_off         112249 non-null  float64
 14  perc_state_error       112249 non-null  float64
dtypes: float64(12), int64(1), str(2)
memory usage: 12.8 MB

In [8]:
w_station_df = pd.read_csv(raw_path / "hourly_pv_weather_station.csv")

In [9]:
w_station_df.head()

,station_hash_id,measured_ts,total_produced_energy,source,ac_power,dc_power,efficiency,device_temperature,perc_state_on,perc_state_off,...,global_tilted_irradiance,terrestrial_radiation,terrestrial_radiation_instant,global_tilted_irradiance_instant,direct_normal_irradiance_instant,diffuse_radiation_instant,direct_radiation_instant,shortwave_radiation_instant,tilt,azimuth
0,19477f81a2058c850a09310b7795fd4f,2024-12-31 23:00:00,0.00,2,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.00000,3.784283,0.0,0.0,-3.58,0.0,1025.3312,25.0,0.0
1,19477f81a2058c850a09310b7795fd4f,2025-01-01 03:00:00,0.00,2,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.00000,4.024922,0.0,0.0,-3.73,0.0,1025.0071,25.0,0.0
2,19477f81a2058c850a09310b7795fd4f,2025-01-01 04:00:00,0.00,2,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,...,0.000000,0.00000,4.349896,0.0,0.0,-3.78,0.0,1024.8055,25.0,0.0
3,19477f81a2058c850a09310b7795fd4f,2025-01-01 05:00:00,0.00,2,0.000000,0.000000,0.000000,6.483333,0.000000,1.000000,...,0.000000,0.00000,4.991553,0.0,0.0,-3.78,0.0,1024.9994,25.0,0.0
4,19477f81a2058c850a09310b7795fd4f,2025-01-01 06:00:00,0.43,2,0.471833,0.554747,75.628333,23.558333,0.916667,0.083333,...,117.665184,112.79406,4.916340,0.0,0.0,-3.73,0.0,1025.1003,25.0,0.0

In [10]:
w_station_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 17983 entries, 0 to 17982
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   station_hash_id                   17983 non-null  str
 1   measured_ts                       17983 non-null  str
 2   total_produced_energy             17983 non-null  float64
 3   source                            17983 non-null  int64
 4   ac_power                          17983 non-null  float64
 5   dc_power                          17983 non-null  float64
 6   efficiency                        17983 non-null  float64
 7   device_temperature                17983 non-null  float64
 8   perc_state_on                     17983 non-null  float64
 9   perc_state_off                    17983 non-null  float64
 10  perc_state_error                  17983 non-null  float64
 11  temperature_2m                    17983 non-null  float64
 12  shortwave_radiation               17983 non-null  float64
 13  direct_radiation                  17983 non-null  float64
 14  diffuse_radiation                 17983 non-null  float64
 15  direct_normal_irradiance          17983 non-null  float64
 16  global_tilted_irradiance          17983 non-null  float64
 17  terrestrial_radiation             17983 non-null  float64
 18  terrestrial_radiation_instant     17983 non-null  float64
 19  global_tilted_irradiance_instant  17983 non-null  float64
 20  direct_normal_irradiance_instant  17983 non-null  float64
 21  diffuse_radiation_instant         17983 non-null  float64
 22  direct_radiation_instant          17983 non-null  float64
 23  shortwave_radiation_instant       17983 non-null  float64
 24  tilt                              17983 non-null  float64
 25  azimuth                           17983 non-null  float64
dtypes: float64(23), int64(1), str(2)
memory usage: 3.6 MB

In [11]:
clients = {sid: g for sid, g in w_station_df.groupby("station_hash_id")}

In [12]:
type(clients)

dict

In [13]:
print(len(clients.keys()))

7

In [36]:
clients["19477f81a2058c850a09310b7795fd4f"].tail()

,station_hash_id,measured_ts,total_produced_energy,source,ac_power,dc_power,efficiency,device_temperature,perc_state_on,perc_state_off,...,global_tilted_irradiance,terrestrial_radiation,terrestrial_radiation_instant,global_tilted_irradiance_instant,direct_normal_irradiance_instant,diffuse_radiation_instant,direct_radiation_instant,shortwave_radiation_instant,tilt,azimuth
2465,19477f81a2058c850a09310b7795fd4f,2025-05-31 19:00:00,0.0,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.804984,24.0,1.0,13.82,0.0,1010.93384,25.0,0.0
2466,19477f81a2058c850a09310b7795fd4f,2025-05-31 20:00:00,0.0,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,1.451206,8.0,0.0,13.82,0.0,1011.29474,25.0,0.0
2467,19477f81a2058c850a09310b7795fd4f,2025-05-31 21:00:00,0.0,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,2.995797,1.0,0.0,13.12,0.0,1011.34576,25.0,0.0
2468,19477f81a2058c850a09310b7795fd4f,2025-05-31 22:00:00,0.0,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,4.080882,1.0,0.0,12.17,0.0,1011.59850,25.0,0.0
2469,19477f81a2058c850a09310b7795fd4f,2025-05-31 23:00:00,0.0,2,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,4.965521,0.0,0.0,11.47,0.0,1011.57184,25.0,0.0

In [14]:
clients["19477f81a2058c850a09310b7795fd4f"].info()

<class 'pandas.DataFrame'>
RangeIndex: 2470 entries, 0 to 2469
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   station_hash_id                   2470 non-null   str
 1   measured_ts                       2470 non-null   str
 2   total_produced_energy             2470 non-null   float64
 3   source                            2470 non-null   int64
 4   ac_power                          2470 non-null   float64
 5   dc_power                          2470 non-null   float64
 6   efficiency                        2470 non-null   float64
 7   device_temperature                2470 non-null   float64
 8   perc_state_on                     2470 non-null   float64
 9   perc_state_off                    2470 non-null   float64
 10  perc_state_error                  2470 non-null   float64
 11  temperature_2m                    2470 non-null   float64
 12  shortwave_radiation               2470 non-null   float64
 13  direct_radiation                  2470 non-null   float64
 14  diffuse_radiation                 2470 non-null   float64
 15  direct_normal_irradiance          2470 non-null   float64
 16  global_tilted_irradiance          2470 non-null   float64
 17  terrestrial_radiation             2470 non-null   float64
 18  terrestrial_radiation_instant     2470 non-null   float64
 19  global_tilted_irradiance_instant  2470 non-null   float64
 20  direct_normal_irradiance_instant  2470 non-null   float64
 21  diffuse_radiation_instant         2470 non-null   float64
 22  direct_radiation_instant          2470 non-null   float64
 23  shortwave_radiation_instant       2470 non-null   float64
 24  tilt                              2470 non-null   float64
 25  azimuth                           2470 non-null   float64
dtypes: float64(23), int64(1), str(2)
memory usage: 501.8 KB

In [44]:
# OUT = Path("../data/processed/client")
# OUT.mkdir(parents=True, exist_ok=True)

# for sid, df in w_station_df.groupby("station_hash_id"): 
#     df.sort_values("measured_ts").to_csv(OUT / f"{sid}.csv", index=False)

In [15]:
df = clients["19477f81a2058c850a09310b7795fd4f"]

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2470 entries, 0 to 2469
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   station_hash_id                   2470 non-null   str
 1   measured_ts                       2470 non-null   str
 2   total_produced_energy             2470 non-null   float64
 3   source                            2470 non-null   int64
 4   ac_power                          2470 non-null   float64
 5   dc_power                          2470 non-null   float64
 6   efficiency                        2470 non-null   float64
 7   device_temperature                2470 non-null   float64
 8   perc_state_on                     2470 non-null   float64
 9   perc_state_off                    2470 non-null   float64
 10  perc_state_error                  2470 non-null   float64
 11  temperature_2m                    2470 non-null   float64
 12  shortwave_radiation               2470 non-null   float64
 13  direct_radiation                  2470 non-null   float64
 14  diffuse_radiation                 2470 non-null   float64
 15  direct_normal_irradiance          2470 non-null   float64
 16  global_tilted_irradiance          2470 non-null   float64
 17  terrestrial_radiation             2470 non-null   float64
 18  terrestrial_radiation_instant     2470 non-null   float64
 19  global_tilted_irradiance_instant  2470 non-null   float64
 20  direct_normal_irradiance_instant  2470 non-null   float64
 21  diffuse_radiation_instant         2470 non-null   float64
 22  direct_radiation_instant          2470 non-null   float64
 23  shortwave_radiation_instant       2470 non-null   float64
 24  tilt                              2470 non-null   float64
 25  azimuth                           2470 non-null   float64
dtypes: float64(23), int64(1), str(2)
memory usage: 501.8 KB

In [18]:
df["measured_ts"] = pd.to_datetime(df["measured_ts"])

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2470 entries, 0 to 2469
Data columns (total 26 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   station_hash_id                   2470 non-null   str
 1   measured_ts                       2470 non-null   datetime64[us]
 2   total_produced_energy             2470 non-null   float64
 3   source                            2470 non-null   int64
 4   ac_power                          2470 non-null   float64
 5   dc_power                          2470 non-null   float64
 6   efficiency                        2470 non-null   float64
 7   device_temperature                2470 non-null   float64
 8   perc_state_on                     2470 non-null   float64
 9   perc_state_off                    2470 non-null   float64
 10  perc_state_error                  2470 non-null   float64
 11  temperature_2m                    2470 non-null   float64
 12  shortwave_radiation               2470 non-null   float64
 13  direct_radiation                  2470 non-null   float64
 14  diffuse_radiation                 2470 non-null   float64
 15  direct_normal_irradiance          2470 non-null   float64
 16  global_tilted_irradiance          2470 non-null   float64
 17  terrestrial_radiation             2470 non-null   float64
 18  terrestrial_radiation_instant     2470 non-null   float64
 19  global_tilted_irradiance_instant  2470 non-null   float64
 20  direct_normal_irradiance_instant  2470 non-null   float64
 21  diffuse_radiation_instant         2470 non-null   float64
 22  direct_radiation_instant          2470 non-null   float64
 23  shortwave_radiation_instant       2470 non-null   float64
 24  tilt                              2470 non-null   float64
 25  azimuth                           2470 non-null   float64
dtypes: datetime64[us](1), float64(23), int64(1), str(1)
memory usage: 501.8 KB

In [ ]:
df.