In [2]:
import pandas as pd 

df = pd.read_csv("../results/test_evaluation_detail.csv")

print(df.shape)
print(df.columns)

(70, 7)
Index(['seed', 'client', 'method', 'n_test', 'mae', 'rmse', 'skill'], dtype='str')

## Examine the row

In [6]:
display(df.head())
display(df.tail())

display(df.sample(5, random_state=0))

   seed client       method  n_test       mae      rmse     skill
0     0     S1  central_mlp     263  0.119135  0.168609  0.088268
1     0     S2  central_mlp     229  0.128589  0.181835  0.028365
2     0     S3  central_mlp     252  0.123262  0.174373  0.045056
3     0     S4  central_mlp     249  0.118496  0.168876  0.030424
4     0     S5  central_mlp     249  0.132596  0.176169  0.153929

    seed client      method  n_test       mae      rmse     skill
65     4     S3  fedprox_e1     252  0.121798  0.168720  0.056394
66     4     S4  fedprox_e1     249  0.109813  0.153445  0.101471
67     4     S5  fedprox_e1     249  0.127552  0.168619  0.186115
68     4     S6  fedprox_e1     247  0.120870  0.160095  0.189096
69     4     S7  fedprox_e1     605  0.179596  0.239872 -0.197434

    seed client       method  n_test       mae      rmse     skill
26     1     S6   fedprox_e1     247  0.119863  0.158338  0.195851
27     1     S7   fedprox_e1     605  0.182810  0.242462 -0.218857
48     3     S7  central_mlp     605  0.159649  0.223573 -0.064440
22     1     S2   fedprox_e1     229  0.124583  0.171568  0.058635
30     2     S3  central_mlp     252  0.115001  0.170932  0.109053

In [8]:
display(df.sample(10, random_state=42))

    seed client       method  n_test       mae      rmse     skill
22     1     S2   fedprox_e1     229  0.124583  0.171568  0.058635
0      0     S1  central_mlp     263  0.119135  0.168609  0.088268
49     3     S1   fedprox_e1     263  0.115958  0.161133  0.112583
4      0     S5  central_mlp     249  0.132596  0.176169  0.153929
54     3     S6   fedprox_e1     247  0.124736  0.161986  0.163157
18     1     S5  central_mlp     249  0.144238  0.197081  0.079649
10     0     S4   fedprox_e1     249  0.113256  0.156162  0.073299
33     2     S6  central_mlp     247  0.132503  0.173010  0.111051
45     3     S4  central_mlp     249  0.128098  0.185689 -0.048143
12     0     S6   fedprox_e1     247  0.128779  0.167563  0.136033

## Check the data types

In [9]:
df.dtypes

seed        int64
client        str
method        str
n_test      int64
mae       float64
rmse      float64
skill     float64
dtype: object

In [10]:
# Check the missing vaues
df.isna().sum()

seed      0
client    0
method    0
n_test    0
mae       0
rmse      0
skill     0
dtype: int64

## Check the categorical values

In [12]:
print(df["method"].value_counts())

print(df["seed"].value_counts().sort_index())

print(df["client"].value_counts())

method
central_mlp    35
fedprox_e1     35
Name: count, dtype: int64
seed
0    14
1    14
2    14
3    14
4    14
Name: count, dtype: int64
client
S1    10
S2    10
S3    10
S4    10
S5    10
S6    10
S7    10
Name: count, dtype: int64